### ISSUE TITLE
Add CI tests/deployment

### ISSUE THREAD

**Issue by JordanSussman** [target/gelvedere#3]
The `.drone.yml` will look like:

```yml
workspace:
  base: /go
  path: src/github.com/target/gelvedere

pipeline:
  test:
    image: golang:1.9
    commands:
      - go test -cover $(go list ./... | grep -v /vendor/)
      - go build -ldflags '-extldflags "-static" -X github.com/target/gelvedere/version.VersionDev=build.'${DRONE_BUILD_NUMBER} -o release/gelvedere github.com/target/gelvedere/cmd/gelvedere

  build_cli:
    image: karalabe/xgo-latest
    when:
      event: tag
    commands:
      - go get -u github.com/karalabe/xgo
      - xgo -out gelvedere -targets=darwin/*,linux/386,linux/amd64 github.com/target/gelvedere/cmd/gelvedere
      - ./build-release.sh

  github_release:
    image: plugins/github-release:latest
    pull: true
    files:
      - release/gelvedere-darwin-386.tgz
      - release/gelvedere-darwin-amd64.tgz
      - release/gelvedere-linux-386.tgz
      - release/gelvedere-linux-amd64.tgz
    checksum:
      - sha256
      - sha512
    when:
      event: tag
    secrets: [ github_token ]
```

The `build-release.sh` will look like:

```bash
#!/bin/bash

name="gelvedere"
if [ ! -d release ]; then mkdir release; fi
mv /build/* release
cd release

# Wipe versions
for n in $(ls *darwin*); do mv $n $(echo $n | sed -r -e 's/-[0-9]+\.[0-9]+-/-/g'); done

for n in $(ls *$name-*)
do
  platform=$(echo $n | awk -F- '{print $2}')
  arch=$(echo $n | awk -F- '{print $3}' | sed -e 's/.exe//g')

  archive_cmd="tar czf ${name}-${platform}-${arch}.tgz ${name}"

  mv $n ${name}
  eval $archive_cmd

  rm -f ${name}
done
```

Unfortunately, this is blocked till I have approval to setup the drone server in the DMZ.
